# Generated by Django 6.0.8 on 2026-09-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gruntwork", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gruntworkdeployment",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalgruntworkdeployment",
            name="configuration",
        ),
    ]
