# Generated by Django 6.0.8 on 2026-09-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gruntwork', '0002_drop_unused_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruntworkdeployment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalgruntworkdeployment',
            name='tags',
        ),
    ]
